<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="Tests.RCR_VR_HA_Service_ConfigTool_Targets_PUT.TestTargetsPut-20180706111149" tests="2" time="135.650">
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Targets_PUT.TestTargetsPut" name="test_Step1_putRequest" time="10.343"/>
	<testcase classname="Tests.RCR_VR_HA_Service_ConfigTool_Targets_PUT.TestTargetsPut" name="test_Step2_putRequest_error" time="125.307">
		<error message="'504' != '409'
- 504
+ 409
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "C:\Users\SC057441\Desktop\Any\pythonscripts\tokka\yamlgenerator\Requests\Final_Suite\Tests\RCR_VR_HA_Service_ConfigTool_Targets_PUT.py", line 83, in test_Step2_putRequest_error
    self.assertEqual(str(self.response), '409')
AssertionError: '504' != '409'
- 504
+ 409

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\SC057441\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\Users\SC057441\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\Users\SC057441\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\Users\SC057441\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "ConfigToolAutomationPUT.py", line 43, in <module>
    ret = not result.run(tests).wasSuccessful()
  File "C:\Users\SC057441\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xmlrunner\xmlrunner.py", line 416, in run
    test(result)
  File "C:\Users\SC057441\AppData\Local\Programs\Python\Python36-32\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\SC057441\AppData\Local\Programs\Python\Python36-32\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\SC057441\AppData\Local\Programs\Python\Python36-32\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\SC057441\AppData\Local\Programs\Python\Python36-32\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\SC057441\Desktop\Any\pythonscripts\tokka\yamlgenerator\Requests\Final_Suite\Tests\RCR_VR_HA_Service_ConfigTool_Targets_PUT.py", line 57, in test_Step1_putRequest
    loggingAPI.logger.info(metric_key_list, target_list, top_zone_list, bottom_zone_list)
Message: ['total_ar', 'total_adjustments', 'total_cash', 'alos', 'clean_claim_rate', 'denial_rate_zero_pay', 'case_mix_index', 'total_gross_revenue']
Arguments: ([Decimal('1251.0000'), Decimal('1251.2500'), Decimal('1251.0000'), Decimal('2.0000'), Decimal('1251.0000'), Decimal('0.5000'), Decimal('1251.0000'), Decimal('1251.0000')], [Decimal('5000.0000'), Decimal('5000.6900'), Decimal('5000.0000'), Decimal('5.0000'), Decimal('5000.0000'), Decimal('1.0000'), Decimal('5000.0000'), Decimal('5000.0000')], [Decimal('1000.0000'), Decimal('1000.1100'), Decimal('1000.0000'), Decimal('1.0000'), Decimal('1000.0000'), Decimal('0.1000'), Decimal('1000.0000'), Decimal('1000.0000')])
]]>	</system-err>
</testsuite>
